### ISSUE TITLE
Login page has labels inside the input?

### ISSUE THREAD

**Issue by elfjes** [Uninett/argus-htmx-frontend#133]
Is this how the login page is supposed to look? Placing the label inside the text-input-box seems really strange to me:
![image](https://github.com/user-attachments/assets/9f49bb78-c0e7-4c68-80c7-3f65b08b2b89)

Especially since we're overriding the background color of inputs to be white:
![image](https://github.com/user-attachments/assets/aad5b3da-5f25-446e-a8c7-a59f1fa01886)

looks weird.

**Comment by hmpf** [comment]
The pieces I copypasted from had this, we can fix after the demo.

I would prefer them to be more vertical actually, one below the other.

**Comment by elfjes** [comment]
I went ahead and created this login page:

![image](https://github.com/user-attachments/assets/12bb6485-03d9-4c30-9420-6a852e6b2bda)

https://github.com/GEANT/geant-argus/commit/0bacb29c8eed80c5dbdbdca635520c8417afe8e0

feel free to upstream

**Comment by hmpf** [comment]
I've tarted it up a little:

![image](https://github.com/user-attachments/assets/a89fae60-47dc-4ea7-a077-674dd03f1650)

**Comment by hmpf** [comment]
Sikt needs the inner border since we don't have a different color for the background in the inputs.
