### ISSUE TITLE
Incident list queries all incidents in database

### ISSUE THREAD

**Issue by elfjes** [Uninett/argus-htmx-frontend#19]
Currently the indicent list views load all incidents before pagination. 
https://github.com/Uninett/argus-htmx-frontend/blob/8f321d35fdbbe0ceea05d3f652e96f5c41400c6c/src/argus_htmx/incidents/views.py#L25-L26

https://github.com/Uninett/argus-htmx-frontend/blob/8f321d35fdbbe0ceea05d3f652e96f5c41400c6c/src/argus_htmx/incidents/views.py#L81-L83

This causes a massive overhead when many incidents are present (I'm already noticing a significant performance drop with 80 total incidents).

Could this be changed so that only the relevant incidents are loaded (pagination before querying)?

**Comment by hmpf** [comment]
Closed by e5ed22b8069e22dd2c5ed6b2f0f55400ce69b867

**Comment by hmpf** [comment]
This page will itself be replaced with a page using a table. Probably next week.
